[package]
name = "doomthing"
description = "doomthing"
version = "1.0.0"
authors = ["LukeGrahamLandry"]
edition = "2021"

[dependencies]
maze = { path = "maze", version = "0.1.0" }

[dependencies.sdl2]
version = "0.35"